### ISSUE TITLE
Non-existent entities handling

### ISSUE THREAD

**Issue by osvetlik** [vanek1821/pia#1]
Currently, when I manually enter an URL with non-existent entity ID, I get ISE 500, but I would like to receive 404 Not Found or be redirected to a list page (ideally with some error message):

http://localhost:8080/userList/user?id=44

![vanek-ise500](https://user-images.githubusercontent.com/16480390/71839410-5f0e1f00-30bb-11ea-835b-4cd768e136d1.png)

This issue is a blocker and must be fixed.

**Comment by vanek1821** [comment]
Fixed in latest commit.

Currently working on Invoice editing
