### ISSUE TITLE
th:field binding

### ISSUE THREAD

**Issue by vanek1821** [vanek1821/pia#2]
In editInvoice.html ( line 69-73 ) I commented adding item values into the th:field, which throws binding error and I don`t know why.. I solved it by filling inputs with into the th:value of the input. What was the mistake?

**Comment by osvetlik** [comment]
This should be a good inspiration:
https://www.baeldung.com/thymeleaf-list

**Comment by vanek1821** [comment]
Thank you. Problem solved
